### ISSUE TITLE
I might find  a bug in the "def transaction_prop" of "class FullTransaction"

### ISSUE THREAD

**Issue by matrixEE** [maher243/BlockSim#4]
The code " t= tx" would not copy tx to t, it means that t and tx are the same object in python. Hence, the "t.timestamp[1] = t.timestamp[1] + Network.tx_prop_delay() " would change the value "tx.timestamp[1]" and the code "t.timestamp[1] = t.timestamp[1] + Network.tx_prop_delay() " would make a bug that the delay of the transaction wuld be more and mode big.
I think that the code " t= tx" should be written as t= copy.deepcopy(tx).

**Comment by maher243** [comment]
Thanks! i fixed it.
